# Generated by Django 2.0.8 on 2018-08-31 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micropost',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='micropost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='micropost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
