# Generated by Django 2.0.8 on 2018-08-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0002_auto_20180831_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropost',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
            preserve_default=False,
        ),
    ]
