# Generated by Django 2.0.8 on 2018-09-01 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0003_micropost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='content',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='micropost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
